### ISSUE TITLE
Null Pointer Thrown on Commands After Using /ba quit

### ISSUE THREAD

**Issue by Bunnyday** [mrdarcychen/BlockyArena#23]
I recently installed the latest version of this and using the wiki, set up an arena and a kit. When testing however, if a player uses the /ba join solo or doubles then uses /ba quit, the plugin throws a null pointer exception if the user then tries to use /ba join solo again in the same session. Workaround requires the player to log out of the server and log back in. However, at one point, the server itself needed to be restarted to avoid the null pointer exception occurring. 

[ERROR] Error occurred while executing command 'ba join solo' for source EntityPlayerMP['BunnyDay'/6439, l='world', x=10644.35, y=11.00, z=9572.09]: null
[11-Sep-2019 08:32:38] java.lang.IllegalStateException: null
[11-Sep-2019 08:32:38] at org.spongepowered.api.world.Location.getExtent(Location.java:161) ~[Location.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at org.spongepowered.api.entity.Transform.<init>(Transform.java:120) ~[Transform.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at org.spongepowered.api.entity.Transform.setLocation(Transform.java:161) ~[Transform.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityTeleportEvent(EntityUtil.java:322) ~[EntityUtil.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at net.minecraft.entity.Entity.setLocation(Entity.java:5378) ~[vg.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.entity.Entity.setLocationAndRotation(Entity.java:5352) ~[vg.class:?]
[11-Sep-2019 08:32:38] at net.huskycraft.blockyarena.utils.Gamer.spawnAt(Gamer.java:86) ~[Gamer.class:?]
[11-Sep-2019 08:32:38] at net.huskycraft.blockyarena.utils.Gamer.join(Gamer.java:153) ~[Gamer.class:?]
[11-Sep-2019 08:32:38] at net.huskycraft.blockyarena.commands.CmdJoin.execute(CmdJoin.java:67) ~[CmdJoin.class:?]
[11-Sep-2019 08:32:38] at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960) [pa.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939) [pa.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
[11-Sep-2019 08:32:38] at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlg000(SourceFile:539) [hv$1.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
[11-Sep-2019 08:32:38] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
[11-Sep-2019 08:32:38] at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
[11-Sep-2019 08:32:38] at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
[11-Sep-2019 08:32:38] at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2768-7.1.4]
[11-Sep-2019 08:32:38] at net.minecraft.server.MinecraftServer.redirect$onRun$zjk000(MinecraftServer.java:3970) [MinecraftServer.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
[11-Sep-2019 08:32:38] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
[11-Sep-2019 08:32:38] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]

**Comment by mrdarcychen** [comment]
Thanks for reporting the issue. Are you using a multi-world setup? It seems like the world was unloaded because there was an IllegalStateException when Sponge was trying to access the world containing the arena. I don't see a NullPointerException in the provided log though. Please ensure that the plugin was successfully loaded during server start up. Corrupt config files may cause errors so if the problem persists, deleting the `config/blockyarena/arenas` folder may help.

**Comment by Bunnyday** [comment]
Yes I am using a multi-world setup. I thought you were possibly dealing
with that since the first time I call the /ba join solo I am in my main
world and then get sent to the world where my pvp arena is. The error only
occurs after that. I have not actually tested having an actual pvp fight
yet so I don't know how that would react yet.

As far as null pointer exception I was referring to this: [ERROR] Error
occurred while executing command 'ba join solo' for source
EntityPlayerMP['BunnyDay'/6439, l='world', x=10644.35, y=11.00, z=9572.09]:
null
And the fact that the Minecraft chat sends this error message: Error
occurred while executing command: null

Sorry if that caused any confusion.

I'll try deleting the file and see what happens.

Thank you!

**Comment by Bunnyday** [comment]
Thank you that worked. The file must have been corrupted.

I have a couple of questions -

What are the spawn a and b points for - once someone uses the /ba join solo
or doubles, it sends them to the "lobby" area where they can use the
command /ba kit - but once you do all that there doesn't seem to be a
command to send you to either spawn point a or b?

Also, I was reading in your changelogs on Sponge that you had made it so
you could create classes. But I couldn't get that to work. Is that
something being implemented later?

Thank you again!

**Comment by mrdarcychen** [comment]
A match will start automatically when the minimum starting requirement for that game mode is met. For instance, you need exactly two players to start a solo match, so once you execute `/ba join solo`, you will have to wait in the lobby until another player also executes the join command. After that you and your opponent will be automatically teleported to those spawn points.

Kits were being referred to as classes in older versions, so there's no difference between the two.

Feel free to checkout our Discord if you have more questions :)
