### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by artimis22** [mrdarcychen/BlockyArena#8]
so i get this error when i put the plugin into my mods folder and start my server. Any idea what this is?

any idea why im getting this error?

[16:04:44] [Server thread/ERROR] [Sponge]: Could not pass FMLPreInitializationEvent to Plugin{id=blockyarena, name=BlockyArena, version=0.3.0, description=Players are able to retrieve items with enchantments., source=C:\Users\DebbieY\Desktop\test\mods\blockyarena-0.3.0.jar} java.lang.NoClassDefFoundError: org/spongepowered/api/item/Enchantment at net.huskycraft.blockyarena.managers.PlayerClassManager.(PlayerClassManager.java:28) ~[PlayerClassManager.class:?] at net.huskycraft.blockyarena.BlockyArena.onPreInit(BlockyArena.java:84) ~[BlockyArena.class:?] at org.spongepowered.common.event.listener.GamePreInitializationEventListener_BlockyArena_onPreInit3.handle(Unknown Source) ~[?:?] at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-2555-7.1.0-BETA-2845] at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:338) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2845] at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:371) [SpongeModEventManager.class:1.12.2-2555-7.1.0-BETA-2845] at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:213) [SpongeImpl.class:1.12.2-2555-7.1.0-BETA-2845] at org.spongepowered.mod.SpongeMod.onStateEvent(SpongeMod.java:232) [SpongeMod.class:1.12.2-2555-7.1.0-BETA-2845] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161] at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?] at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?] at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253) [LoadController.class:?] at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231) [LoadController.class:?] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_161] at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_161] at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_161] at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76) [minecraft_server.1.12.2.jar:?] at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116) [minecraft_server.1.12.2.jar:?] at com.google.common.eventbus.EventBus.post(EventBus.java:217) [minecraft_server.1.12.2.jar:?] at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:560) [LoadController.class:?] at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148) [LoadController.class:?] at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602) [Loader.class:?] at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98) [FMLServerHandler.class:?] at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:331) [FMLCommonHandler.class:?] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484) [MinecraftServer.class:?] at java.lang.Thread.run(Unknown Source) [?:1.8.0_161] Caused by: java.lang.ClassNotFoundException: org.spongepowered.api.item.Enchantment at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161] … 40 more Caused by: java.lang.NullPointerException at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161] at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161] … 40 more

**Comment by mrdarcychen** [comment]
Hi artimis22,
Sorry for the late response. The official release of API 7.0.0 deprecates several functions related to item enchantments, therefore causing this error. I'm working on an update which will be released really soon.
